version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./www:/var/www/html
    environment:
      - PHP_CLI_SERVER_WORKERS=4

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laragon
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
